[package]
name = "headless"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
abstio = { path = "../abstio" }
abstutil = { path = "../abstutil" }
anyhow = "1.0.37"
geojson = "0.21.0"
geom = { path = "../geom" }
hyper = "0.13.9"
lazy_static = "1.4.0"
log = "0.4.11"
map_model = { path = "../map_model" }
rand = "0.8.1"
rand_xorshift = "0.3.0"
serde = "1.0.116"
serde_json = "1.0.61"
sim = { path = "../sim" }
tokio = { version = "0.2.22", features = ["full"] }
url = "2.2.0"
