[package]
name = "map_model"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
abstutil = { path = "../abstutil" }
enumset = { version = "1.0.1", features=["serde"] }
fast_paths = { git = "https://github.com/easbar/fast_paths" }
geom = { path = "../geom" }
log = "0.4.11"
nbez = "0.1.0"
petgraph = "0.5.1"
rand = "0.7.0"
rand_xorshift = "0.2.0"
serde = "1.0.116"
serde_json = "1.0.40"
thread_local = "1.0.1"
traffic_signal_data = { path = "../traffic_signal_data" }
