[package]
name = "traffic_seitan"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
abstutil = { path = "../abstutil" }
geom = { path = "../geom" }
map_model = { path = "../map_model" }
rand = "0.8.1"
rand_xorshift = "0.3.0"
sim = { path = "../sim" }
