[package]
name = "traffic_signal_data"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
include_dir = "0.5.0"
serde = "1.0.89"
serde_derive = "1.0.98"
serde_json = "1.0.40"
