[package]
name = "abstio"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
abstutil = { path = "../abstutil" }
anyhow = "1.0.37"
bincode = "1.3.1"
instant = "0.1.7"
lazy_static = "1.4.0"
log = "0.4.11"
serde = "1.0.116"
serde_json = "1.0.61"

[target.'cfg(target_arch = "wasm32")'.dependencies]
include_dir = { git = "https://github.com/dabreegster/include_dir", branch = "union" }
web-sys = { version = "0.3.4", features=["Storage", "Window"] }
